name: Lint

on: [pull_request]

jobs:
  merge-conflict:
    name: Merge Conflict
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check merge conflict
        run: grep "^<<<<<<< HEAD" $(git ls-files | xargs) && exit 1 || true
  trailing-whitespace:
    name: Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for trailing whitespace
        run: "! git grep -EIn $'[ \t]+$'"
